(display 'a)
(newline)
(display '(1 2 3))
(newline)
(display (car '(1 2 3)))
(define y '(a x + b))
(newline)
(display (car y))
(newline)
(display (cadr y))
(newline)
(display (caddr y))
(newline)
(display (cadddr y))
(exit)